FROM golang:alpine 

RUN apk update && apk add --no-cache bash git

COPY . /go/src/transaction-server/
RUN go get /go/src/transaction-server 
RUN go install /go/src/transaction-server

ENTRYPOINT /go/bin/transaction-server

